FROM node:20-alpine

ENV NODE_ENV=development

WORKDIR /app

# For using in healthcheck
RUN apk add --no-cache curl

COPY package.json package-lock.json ./
# --legacy-peer-deps due to openai expects zod@^3
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 3001
EXPOSE 51204

CMD ["npm", "run", "start:dev"]