export const AI_ERROR_TYPE = {
  OPENAI_API_ERROR: "OPENAI_API_ERROR",
  PARSE_TASK_VAGUE_INPUT_ERROR: "PARSE_TASK_VAGUE_INPUT_ERROR",
  PROMPT_INJECTION_DETECTED: "PROMPT_INJECTION_DETECTED",
  RABBITMQ_SEND_MESSAGE_TO_QUEUE_FAILED:
    "RABBITMQ_SEND_MESSAGE_TO_QUEUE_FAILED",
  RABBITMQ_CONSUME_MESSAGE_FAILED: "RABBITMQ_CONSUME_MESSAGE_FAILED",
} as const;
