FROM node:20-alpine

ENV NODE_ENV=development

WORKDIR /app

# For using in healthcheck
RUN apk add --no-cache curl

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3001
EXPOSE 51204

CMD ["npm", "run", "start:dev"]