import dotenv from "dotenv";
import { cleanEnv, num, port, str, url } from "envalid";

dotenv.config();

export const env = cleanEnv(process.env, {
  SERVICE_NAME: str(),
  SERVICE_PORT: port(),
  SERVICE_URL: url(),

  AI_SERVICE_URL: str(),

  DATABASE_URL: str(),

  REDIS_URL: str(),
  REDIS_CONNECT_TIMEOUT_MS: num(),
  REDIS_READY_TIMEOUT_MS: num(),

  REDLOCK_RETRY_COUNT: num(),
  REDLOCK_RETRY_DELAY_MS: num(),
  REDLOCK_RETRY_JITTER_MS: num(),

  API_TOKEN_BUCKET_RATE_LIMITER_NAME: str(),
  API_TOKEN_BUCKET_RATE_LIMITER_BUCKET_SIZE: num(),
  API_TOKEN_BUCKET_RATE_LIMITER_REFILL_RATE: num(),
  API_TOKEN_BUCKET_RATE_LIMITER_BUCKET_TTL_SECONDS: num(),
  API_TOKEN_BUCKET_RATE_LIMITER_LOCK_TTL_MS: num(),

  OPENAI_TOKEN_USAGE_RATE_LIMITER_NAME: str(),
  OPENAI_TOKEN_USAGE_RATE_LIMITER_WINDOW_TOKENS_LIMIT: num(),
  OPENAI_TOKEN_USAGE_RATE_LIMITER_WINDOW_SIZE_SECONDS: num(),
  OPENAI_TOKEN_USAGE_RATE_LIMITER_LOCK_TTL_MS: num(),

  CREATE_TASK_ESTIMATED_TOKEN_USAGE: num(),
});
